# Site settings
title: Butane Jekyll Theme
description: >
    This is an example of the Butane Jekyll Theme created by Alex Carpenter
author: Alex Carpenter
email: youemail@gmail.com
baseurl: ""
url: ""
twitter_username: hybrid_alex
github_username:  alexcarpenter

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
